#!/bin/bash

# Tsüklid (loop) Praks6 esimene ülesanne: leia  kümme esimest paaris arvu summa.
summa=0
for (( arv=1; arv<11; arv++ ))
do
	jaak=$(( $arv %2 ))
	if [ $jaak -eq 0 ];
then
	summa=$(( $summa + $arv ))
	echo "$summa"
	fi
done


