#!/bin/bash
## Ülesanne 2: Arvuta täisarvu numbrite summa

	echo "Sisesta täisarv:"
	read arv

summa=0

while [ $arv -ne 0 ]
do
	jaak=$(( $arv % 10 ))
	summa=$(( $summa + $jaak ))
	arv=$(( $arv / 10 ))

	echo "$summa"
done
	echo "täisarvu summa on: $summa"
## proovime FOR-ga
##        echo "Sisesta täisarv:"
###       read arv


