#!/bin/bash
## WHILE tükkel. tubavasta kas tegemist on algarvuga

		echo -n "Sisesta mingi täisarv:"
	read arv
if [ $arv -eq 0 -o $arv -eq 1 ]; then
		echo "$arv - ei ole algarv"
else
	jagaja=2
	jaak=$(($arv % $jagaja))
	while [ $jaak -ne 0 ]
do
	jagaja=$(($jagaja + 1))
	jaak=$(($arv % $jagaja))
done
	if [ $arv -eq $jagaja ]; then
		echo "$arv - on algarv"
else
		echo "$arv - ei ole algarv"
	fi
fi

echo "Ülesande täiendus: anna teada kas esimesed  20 täisarvu on algarvud või mitte"
for arv in {1..20}; do
if [ $arv -eq 0 -o  $arv -eq 1 ]; then
	echo "$arv - ei ole algarv"
else
	jagaja=2
	jaak=$(($arv % $jagaja))
	while [ $jaak -ne 0 ]
do
		jagaja=$(($jagaja + 1))
		jaak=$(($arv % $jagaja))
done
	if [ $arv -eq $jagaja ]; then
		echo "$arv - on algarv"
else
		echo "$arv - ei ole algarv"
	fi
fi
done
