#!/bin/bash
## Sisseehitatud tsüklid - LOOP
### ülesande sisene näidis
for (( i = 1; i <= 5; i++ ))      ### Outer for loop ###
do
    for (( j = 1 ; j <= 5; j++ )) ### Inner for loop ###
    do
          echo -n "$i "
    done
  echo "" #### print the new line ###
done
	echo Ülesanne tärnidega!

for (( i = 1; i <= 5; i++ ))      ### Outer for loop ###
do
	echo -n "$i. "
    for (( j = 1; j <= 5; j++ )) ### Inner for loop ###
    do
          echo -n "* "
    done
  echo "" #### print the new line ###
done
