#!/bin/bash
##Tervitamine vastavalt kellaajale
	echo -e "Palun sisesta kellaaeg: \c"
read aeg

if [ $aeg -ge 6 -a $aeg -lt 12 ]
then
	echo " Tere hommikut!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]
then
        echo " Tere päevast!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]
then
        echo " Head õhtut!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]
then
        echo " Head ööd!"
else
	echo "Olete andmed valesti edastanud. Palun proovige uuesti"

fi
