#!/bin/bash

# Praks2 ülesanded 2
#Skript peab võimaldama tervitada kasutajat.


Nimetaht=$(whoami | cut -c1 | tr [a-z] [A-Z])
Nimetaht2=$(whoami | cut -c2-)

echo "Tere, $Nimetaht$Nimetaht2"
echo "!"
